export const kanjiData = [
  // N5 Kanji
  { kanji: '一', onyomi: 'いち、いつ', kunyomi: 'ひと(つ)', english: 'One', example: '一つ (hitotsu) - one thing', level: 'N5', strokes: 1 },
  { kanji: '二', onyomi: 'に', kunyomi: 'ふた(つ)', english: 'Two', example: '二人 (futari) - two people', level: 'N5', strokes: 2 },
  { kanji: '三', onyomi: 'さん', kunyomi: 'み(つ)', english: 'Three', example: '三月 (sangatsu) - March', level: 'N5', strokes: 3 },
  { kanji: '四', onyomi: 'し', kunyomi: 'よ(つ)、よん', english: 'Four', example: '四時 (yoji) - 4 o\'clock', level: 'N5', strokes: 5 },
  { kanji: '五', onyomi: 'ご', kunyomi: 'いつ(つ)', english: 'Five', example: '五月 (gogatsu) - May', level: 'N5', strokes: 4 },
  { kanji: '六', onyomi: 'ろく', kunyomi: 'む(つ)', english: 'Six', example: '六時 (rokuji) - 6 o\'clock', level: 'N5', strokes: 4 },
  { kanji: '七', onyomi: 'しち', kunyomi: 'なな(つ)', english: 'Seven', example: '七月 (shichigatsu) - July', level: 'N5', strokes: 2 },
  { kanji: '八', onyomi: 'はち', kunyomi: 'や(つ)', english: 'Eight', example: '八時 (hachiji) - 8 o\'clock', level: 'N5', strokes: 2 },
  { kanji: '九', onyomi: 'きゅう、く', kunyomi: 'ここの(つ)', english: 'Nine', example: '九月 (kugatsu) - September', level: 'N5', strokes: 2 },
  { kanji: '十', onyomi: 'じゅう', kunyomi: 'とお', english: 'Ten', example: '十分 (juppun) - 10 minutes', level: 'N5', strokes: 2 },
  { kanji: '日', onyomi: 'にち、じつ', kunyomi: 'ひ、か', english: 'Day / Sun', example: '日本 (nihon) - Japan', level: 'N5', strokes: 4 },
  { kanji: '月', onyomi: 'げつ、がつ', kunyomi: 'つき', english: 'Month / Moon', example: '月曜日 (getsuyōbi) - Monday', level: 'N5', strokes: 4 },
  { kanji: '年', onyomi: 'ねん', kunyomi: 'とし', english: 'Year', example: '今年 (kotoshi) - this year', level: 'N5', strokes: 6 },
  { kanji: '時', onyomi: 'じ', kunyomi: 'とき', english: 'Time / Hour', example: '何時 (nanji) - what time', level: 'N5', strokes: 10 },
  { kanji: '人', onyomi: 'じん、にん', kunyomi: 'ひと', english: 'Person', example: '日本人 (nihonjin) - Japanese person', level: 'N5', strokes: 2 },
  { kanji: '大', onyomi: 'だい、たい', kunyomi: 'おお(きい)', english: 'Big / Large', example: '大学 (daigaku) - university', level: 'N5', strokes: 3 },
  { kanji: '小', onyomi: 'しょう', kunyomi: 'ちい(さい)、こ', english: 'Small', example: '小学校 (shōgakkō) - elementary school', level: 'N5', strokes: 3 },
  { kanji: '山', onyomi: 'さん', kunyomi: 'やま', english: 'Mountain', example: '富士山 (Fujisan) - Mt. Fuji', level: 'N5', strokes: 3 },
  { kanji: '川', onyomi: 'せん', kunyomi: 'かわ', english: 'River', example: '川 (kawa) - river', level: 'N5', strokes: 3 },
  { kanji: '水', onyomi: 'すい', kunyomi: 'みず', english: 'Water', example: '水曜日 (suiyōbi) - Wednesday', level: 'N5', strokes: 4 },
  { kanji: '火', onyomi: 'か', kunyomi: 'ひ', english: 'Fire', example: '火曜日 (kayōbi) - Tuesday', level: 'N5', strokes: 4 },
  { kanji: '木', onyomi: 'もく、ぼく', kunyomi: 'き', english: 'Tree / Wood', example: '木曜日 (mokuyōbi) - Thursday', level: 'N5', strokes: 4 },
  { kanji: '金', onyomi: 'きん、こん', kunyomi: 'かね', english: 'Gold / Money', example: '金曜日 (kin\'yōbi) - Friday', level: 'N5', strokes: 8 },
  { kanji: '土', onyomi: 'ど、と', kunyomi: 'つち', english: 'Earth / Soil', example: '土曜日 (doyōbi) - Saturday', level: 'N5', strokes: 3 },
  { kanji: '学', onyomi: 'がく', kunyomi: 'まな(ぶ)', english: 'Study / Learn', example: '学校 (gakkō) - school', level: 'N5', strokes: 8 },
  { kanji: '校', onyomi: 'こう', kunyomi: '-', english: 'School', example: '高校 (kōkō) - high school', level: 'N5', strokes: 10 },
  { kanji: '先', onyomi: 'せん', kunyomi: 'さき', english: 'Before / Previous', example: '先生 (sensei) - teacher', level: 'N5', strokes: 6 },
  { kanji: '生', onyomi: 'せい、しょう', kunyomi: 'い(きる)、う(まれる)', english: 'Life / Birth', example: '学生 (gakusei) - student', level: 'N5', strokes: 5 },
  // N4 Kanji
  { kanji: '運', onyomi: 'うん', kunyomi: 'はこ(ぶ)', english: 'Carry / Luck', example: '運動 (undō) - exercise', level: 'N4', strokes: 12 },
  { kanji: '動', onyomi: 'どう', kunyomi: 'うご(く)', english: 'Move', example: '運動 (undō) - exercise', level: 'N4', strokes: 11 },
  { kanji: '医', onyomi: 'い', kunyomi: '-', english: 'Doctor / Medicine', example: '医者 (isha) - doctor', level: 'N4', strokes: 7 },
  { kanji: '者', onyomi: 'しゃ', kunyomi: 'もの', english: 'Person (expert)', example: '医者 (isha) - doctor', level: 'N4', strokes: 8 },
  { kanji: '料', onyomi: 'りょう', kunyomi: '-', english: 'Fee / Materials', example: '料理 (ryōri) - cooking', level: 'N4', strokes: 10 },
  { kanji: '理', onyomi: 'り', kunyomi: '-', english: 'Reason / Logic', example: '料理 (ryōri) - cooking', level: 'N4', strokes: 11 },
  { kanji: '建', onyomi: 'けん', kunyomi: 'た(てる)', english: 'Build / Construct', example: '建物 (tatemono) - building', level: 'N4', strokes: 9 },
  { kanji: '物', onyomi: 'ぶつ、もつ', kunyomi: 'もの', english: 'Thing / Object', example: '食べ物 (tabemono) - food', level: 'N4', strokes: 8 },
  { kanji: '映', onyomi: 'えい', kunyomi: 'うつ(る)', english: 'Reflect / Project', example: '映画 (eiga) - movie', level: 'N4', strokes: 9 },
  { kanji: '画', onyomi: 'が、かく', kunyomi: 'えが(く)', english: 'Picture / Draw', example: '映画 (eiga) - movie', level: 'N4', strokes: 8 },
  { kanji: '旅', onyomi: 'りょ', kunyomi: 'たび', english: 'Travel', example: '旅行 (ryokō) - travel', level: 'N4', strokes: 10 },
  { kanji: '行', onyomi: 'こう、ぎょう', kunyomi: 'い(く)、おこな(う)', english: 'Go / Conduct', example: '旅行 (ryokō) - travel', level: 'N4', strokes: 6 },
  { kanji: '場', onyomi: 'じょう', kunyomi: 'ば', english: 'Place / Situation', example: '場所 (basho) - place', level: 'N4', strokes: 12 },
  { kanji: '所', onyomi: 'しょ', kunyomi: 'ところ', english: 'Place', example: '場所 (basho) - place', level: 'N4', strokes: 8 },
  { kanji: '交', onyomi: 'こう', kunyomi: 'まじ(わる)', english: 'Intersect / Exchange', example: '交通 (kōtsū) - traffic', level: 'N4', strokes: 6 },
  { kanji: '通', onyomi: 'つう', kunyomi: 'とお(る)', english: 'Pass Through', example: '交通 (kōtsū) - traffic', level: 'N4', strokes: 10 },
];