export const katakanaData = [
  { kana: 'ア', romaji: 'a', hiragana: 'あ' },
  { kana: 'イ', romaji: 'i', hiragana: 'い' },
  { kana: 'ウ', romaji: 'u', hiragana: 'う' },
  { kana: 'エ', romaji: 'e', hiragana: 'え' },
  { kana: 'オ', romaji: 'o', hiragana: 'お' },
  { kana: 'カ', romaji: 'ka', hiragana: 'か' },
  { kana: 'キ', romaji: 'ki', hiragana: 'き' },
  { kana: 'ク', romaji: 'ku', hiragana: 'く' },
  { kana: 'ケ', romaji: 'ke', hiragana: 'け' },
  { kana: 'コ', romaji: 'ko', hiragana: 'こ' },
  { kana: 'サ', romaji: 'sa', hiragana: 'さ' },
  { kana: 'シ', romaji: 'shi', hiragana: 'し' },
  { kana: 'ス', romaji: 'su', hiragana: 'す' },
  { kana: 'セ', romaji: 'se', hiragana: 'せ' },
  { kana: 'ソ', romaji: 'so', hiragana: 'そ' },
  { kana: 'タ', romaji: 'ta', hiragana: 'た' },
  { kana: 'チ', romaji: 'chi', hiragana: 'ち' },
  { kana: 'ツ', romaji: 'tsu', hiragana: 'つ' },
  { kana: 'テ', romaji: 'te', hiragana: 'て' },
  { kana: 'ト', romaji: 'to', hiragana: 'と' },
  { kana: 'ナ', romaji: 'na', hiragana: 'な' },
  { kana: 'ニ', romaji: 'ni', hiragana: 'に' },
  { kana: 'ヌ', romaji: 'nu', hiragana: 'ぬ' },
  { kana: 'ネ', romaji: 'ne', hiragana: 'ね' },
  { kana: 'ノ', romaji: 'no', hiragana: 'の' },
  { kana: 'ハ', romaji: 'ha', hiragana: 'は' },
  { kana: 'ヒ', romaji: 'hi', hiragana: 'ひ' },
  { kana: 'フ', romaji: 'fu', hiragana: 'ふ' },
  { kana: 'ヘ', romaji: 'he', hiragana: 'へ' },
  { kana: 'ホ', romaji: 'ho', hiragana: 'ほ' },
  { kana: 'マ', romaji: 'ma', hiragana: 'ま' },
  { kana: 'ミ', romaji: 'mi', hiragana: 'み' },
  { kana: 'ム', romaji: 'mu', hiragana: 'む' },
  { kana: 'メ', romaji: 'me', hiragana: 'め' },
  { kana: 'モ', romaji: 'mo', hiragana: 'も' },
  { kana: 'ヤ', romaji: 'ya', hiragana: 'や' },
  { kana: 'ユ', romaji: 'yu', hiragana: 'ゆ' },
  { kana: 'ヨ', romaji: 'yo', hiragana: 'よ' },
  { kana: 'ラ', romaji: 'ra', hiragana: 'ら' },
  { kana: 'リ', romaji: 'ri', hiragana: 'り' },
  { kana: 'ル', romaji: 'ru', hiragana: 'る' },
  { kana: 'レ', romaji: 're', hiragana: 'れ' },
  { kana: 'ロ', romaji: 'ro', hiragana: 'ろ' },
  { kana: 'ワ', romaji: 'wa', hiragana: 'わ' },
  { kana: 'ヲ', romaji: 'wo', hiragana: 'を' },
  { kana: 'ン', romaji: 'n', hiragana: 'ん' },
  // Common loan words
  { kana: 'ガ', romaji: 'ga', hiragana: 'が' },
  { kana: 'ギ', romaji: 'gi', hiragana: 'ぎ' },
  { kana: 'グ', romaji: 'gu', hiragana: 'ぐ' },
  { kana: 'ゲ', romaji: 'ge', hiragana: 'げ' },
  { kana: 'ゴ', romaji: 'go', hiragana: 'ご' },
];

export const katakanaWords = [
  { kana: 'コーヒー', romaji: 'kōhī', english: 'Coffee' },
  { kana: 'テレビ', romaji: 'terebi', english: 'Television' },
  { kana: 'コンピューター', romaji: 'konpyūtā', english: 'Computer' },
  { kana: 'スマートフォン', romaji: 'sumātofon', english: 'Smartphone' },
  { kana: 'レストラン', romaji: 'resutoran', english: 'Restaurant' },
  { kana: 'アイスクリーム', romaji: 'aisukurīmu', english: 'Ice Cream' },
  { kana: 'スーパー', romaji: 'sūpā', english: 'Supermarket' },
  { kana: 'バス', romaji: 'basu', english: 'Bus' },
  { kana: 'タクシー', romaji: 'takushī', english: 'Taxi' },
  { kana: 'ホテル', romaji: 'hoteru', english: 'Hotel' },
];