export const vocabularyN5 = [
  // Greetings
  { word: 'おはようございます', romaji: 'ohayō gozaimasu', english: 'Good morning', category: 'Greetings', level: 'N5' },
  { word: 'こんにちは', romaji: 'konnichiwa', english: 'Hello / Good afternoon', category: 'Greetings', level: 'N5' },
  { word: 'こんばんは', romaji: 'konbanwa', english: 'Good evening', category: 'Greetings', level: 'N5' },
  { word: 'さようなら', romaji: 'sayōnara', english: 'Goodbye', category: 'Greetings', level: 'N5' },
  { word: 'ありがとうございます', romaji: 'arigatō gozaimasu', english: 'Thank you very much', category: 'Greetings', level: 'N5' },
  { word: 'すみません', romaji: 'sumimasen', english: 'Excuse me / Sorry', category: 'Greetings', level: 'N5' },
  { word: 'はい', romaji: 'hai', english: 'Yes', category: 'Greetings', level: 'N5' },
  { word: 'いいえ', romaji: 'iie', english: 'No', category: 'Greetings', level: 'N5' },
  // Numbers
  { word: 'いち', romaji: 'ichi', english: 'One (1)', category: 'Numbers', level: 'N5' },
  { word: 'に', romaji: 'ni', english: 'Two (2)', category: 'Numbers', level: 'N5' },
  { word: 'さん', romaji: 'san', english: 'Three (3)', category: 'Numbers', level: 'N5' },
  { word: 'し・よん', romaji: 'shi / yon', english: 'Four (4)', category: 'Numbers', level: 'N5' },
  { word: 'ご', romaji: 'go', english: 'Five (5)', category: 'Numbers', level: 'N5' },
  { word: 'ろく', romaji: 'roku', english: 'Six (6)', category: 'Numbers', level: 'N5' },
  { word: 'しち・なな', romaji: 'shichi / nana', english: 'Seven (7)', category: 'Numbers', level: 'N5' },
  { word: 'はち', romaji: 'hachi', english: 'Eight (8)', category: 'Numbers', level: 'N5' },
  { word: 'く・きゅう', romaji: 'ku / kyū', english: 'Nine (9)', category: 'Numbers', level: 'N5' },
  { word: 'じゅう', romaji: 'jū', english: 'Ten (10)', category: 'Numbers', level: 'N5' },
  { word: 'ひゃく', romaji: 'hyaku', english: 'Hundred (100)', category: 'Numbers', level: 'N5' },
  { word: 'せん', romaji: 'sen', english: 'Thousand (1000)', category: 'Numbers', level: 'N5' },
  // Time
  { word: 'いま', romaji: 'ima', english: 'Now', category: 'Time', level: 'N5' },
  { word: 'きょう', romaji: 'kyō', english: 'Today', category: 'Time', level: 'N5' },
  { word: 'あした', romaji: 'ashita', english: 'Tomorrow', category: 'Time', level: 'N5' },
  { word: 'きのう', romaji: 'kinō', english: 'Yesterday', category: 'Time', level: 'N5' },
  { word: 'まいにち', romaji: 'mainichi', english: 'Every day', category: 'Time', level: 'N5' },
  { word: 'ごぜん', romaji: 'gozen', english: 'AM / Morning', category: 'Time', level: 'N5' },
  { word: 'ごご', romaji: 'gogo', english: 'PM / Afternoon', category: 'Time', level: 'N5' },
  // Family
  { word: 'おかあさん', romaji: 'okāsan', english: 'Mother', category: 'Family', level: 'N5' },
  { word: 'おとうさん', romaji: 'otōsan', english: 'Father', category: 'Family', level: 'N5' },
  { word: 'おにいさん', romaji: 'oniisan', english: 'Older brother', category: 'Family', level: 'N5' },
  { word: 'おねえさん', romaji: 'onēsan', english: 'Older sister', category: 'Family', level: 'N5' },
  { word: 'いもうと', romaji: 'imōto', english: 'Younger sister', category: 'Family', level: 'N5' },
  { word: 'おとうと', romaji: 'otōto', english: 'Younger brother', category: 'Family', level: 'N5' },
  // Food
  { word: 'ごはん', romaji: 'gohan', english: 'Rice / Meal', category: 'Food', level: 'N5' },
  { word: 'みず', romaji: 'mizu', english: 'Water', category: 'Food', level: 'N5' },
  { word: 'パン', romaji: 'pan', english: 'Bread', category: 'Food', level: 'N5' },
  { word: 'さかな', romaji: 'sakana', english: 'Fish', category: 'Food', level: 'N5' },
  { word: 'にく', romaji: 'niku', english: 'Meat', category: 'Food', level: 'N5' },
  { word: 'やさい', romaji: 'yasai', english: 'Vegetables', category: 'Food', level: 'N5' },
  { word: 'くだもの', romaji: 'kudamono', english: 'Fruit', category: 'Food', level: 'N5' },
  // Verbs
  { word: 'たべます', romaji: 'tabemasu', english: 'To eat', category: 'Verbs', level: 'N5' },
  { word: 'のみます', romaji: 'nomimasu', english: 'To drink', category: 'Verbs', level: 'N5' },
  { word: 'いきます', romaji: 'ikimasu', english: 'To go', category: 'Verbs', level: 'N5' },
  { word: 'きます', romaji: 'kimasu', english: 'To come', category: 'Verbs', level: 'N5' },
  { word: 'かえります', romaji: 'kaerimasu', english: 'To return home', category: 'Verbs', level: 'N5' },
  { word: 'みます', romaji: 'mimasu', english: 'To see/watch', category: 'Verbs', level: 'N5' },
  { word: 'ききます', romaji: 'kikimasu', english: 'To listen', category: 'Verbs', level: 'N5' },
  { word: 'よみます', romaji: 'yomimasu', english: 'To read', category: 'Verbs', level: 'N5' },
  { word: 'かきます', romaji: 'kakimasu', english: 'To write', category: 'Verbs', level: 'N5' },
  { word: 'はなします', romaji: 'hanashimasu', english: 'To speak', category: 'Verbs', level: 'N5' },
];

export const vocabularyN4 = [
  // Emotions/Feelings
  { word: 'うれしい', romaji: 'ureshii', english: 'Happy', category: 'Emotions', level: 'N4' },
  { word: 'かなしい', romaji: 'kanashii', english: 'Sad', category: 'Emotions', level: 'N4' },
  { word: 'こわい', romaji: 'kowai', english: 'Scary / Afraid', category: 'Emotions', level: 'N4' },
  { word: 'はずかしい', romaji: 'hazukashii', english: 'Embarrassed', category: 'Emotions', level: 'N4' },
  { word: 'さびしい', romaji: 'sabishii', english: 'Lonely', category: 'Emotions', level: 'N4' },
  { word: 'おどろく', romaji: 'odoroku', english: 'To be surprised', category: 'Emotions', level: 'N4' },
  // Advanced Verbs
  { word: 'あつめる', romaji: 'atsumeru', english: 'To collect/gather', category: 'Verbs', level: 'N4' },
  { word: 'おくる', romaji: 'okuru', english: 'To send', category: 'Verbs', level: 'N4' },
  { word: 'とどける', romaji: 'todokeru', english: 'To deliver', category: 'Verbs', level: 'N4' },
  { word: 'しらべる', romaji: 'shiraberu', english: 'To investigate/check', category: 'Verbs', level: 'N4' },
  { word: 'かんがえる', romaji: 'kangaeru', english: 'To think/consider', category: 'Verbs', level: 'N4' },
  { word: 'えらぶ', romaji: 'erabu', english: 'To choose/select', category: 'Verbs', level: 'N4' },
  { word: 'みつかる', romaji: 'mitsukaru', english: 'To be found', category: 'Verbs', level: 'N4' },
  { word: 'つづける', romaji: 'tsuzukeru', english: 'To continue', category: 'Verbs', level: 'N4' },
  { word: 'やめる', romaji: 'yameru', english: 'To quit/stop', category: 'Verbs', level: 'N4' },
  { word: 'こまる', romaji: 'komaru', english: 'To be troubled', category: 'Verbs', level: 'N4' },
  { word: 'にあう', romaji: 'niau', english: 'To suit/match', category: 'Verbs', level: 'N4' },
  { word: 'つれる', romaji: 'tsureru', english: 'To bring (person)', category: 'Verbs', level: 'N4' },
  { word: 'つく', romaji: 'tsuku', english: 'To arrive', category: 'Verbs', level: 'N4' },
  { word: 'ならぶ', romaji: 'narabu', english: 'To line up', category: 'Verbs', level: 'N4' },
  // Adjectives
  { word: 'あんぜん', romaji: 'anzen', english: 'Safe', category: 'Adjectives', level: 'N4' },
  { word: 'たいせつ', romaji: 'taisetsu', english: 'Important/precious', category: 'Adjectives', level: 'N4' },
  { word: 'とくべつ', romaji: 'tokubetsu', english: 'Special', category: 'Adjectives', level: 'N4' },
  { word: 'ふつう', romaji: 'futsū', english: 'Ordinary/normal', category: 'Adjectives', level: 'N4' },
  { word: 'いろいろ', romaji: 'iroiro', english: 'Various', category: 'Adjectives', level: 'N4' },
  { word: 'たくさん', romaji: 'takusan', english: 'Many/much', category: 'Adjectives', level: 'N4' },
  // Nouns
  { word: 'りゆう', romaji: 'riyū', english: 'Reason', category: 'Nouns', level: 'N4' },
  { word: 'もんだい', romaji: 'mondai', english: 'Problem/question', category: 'Nouns', level: 'N4' },
  { word: 'けいけん', romaji: 'keiken', english: 'Experience', category: 'Nouns', level: 'N4' },
  { word: 'しゅうかん', romaji: 'shūkan', english: 'Habit/custom', category: 'Nouns', level: 'N4' },
  { word: 'しゃかい', romaji: 'shakai', english: 'Society', category: 'Nouns', level: 'N4' },
  { word: 'けんこう', romaji: 'kenkō', english: 'Health', category: 'Nouns', level: 'N4' },
  { word: 'せいかつ', romaji: 'seikatsu', english: 'Life/lifestyle', category: 'Nouns', level: 'N4' },
  { word: 'きかい', romaji: 'kikai', english: 'Opportunity/machine', category: 'Nouns', level: 'N4' },
  { word: 'つごう', romaji: 'tsugō', english: 'Convenience', category: 'Nouns', level: 'N4' },
  { word: 'やくそく', romaji: 'yakusoku', english: 'Promise', category: 'Nouns', level: 'N4' },
];

export const allVocabulary = [...vocabularyN5, ...vocabularyN4];
export const categories = ['All', 'Greetings', 'Numbers', 'Time', 'Family', 'Food', 'Verbs', 'Emotions', 'Adjectives', 'Nouns'];